package com.fvps.backend.domain.enums;

public enum AppMessage {
    // Verification
    ACCESS_GRANTED,
    ACCESS_DENIED_BLOCKED,
    ACCESS_DENIED_NO_TRAINING,
    ACCESS_DENIED_USER_NOT_FOUND,
    ACCESS_DENIED_LOW_LEVEL,

    // Auth
    LOGIN_SUCCESS,
    REGISTER_SUCCESS,
    PASSWORD_RESET_LINK_SENT,
    PASSWORD_RESET_COMPLETE,
    PASSWORD_CHANGE_SUCCESS,

    // User
    PROFILE_UPDATED,
    PASSWORD_CHANGED,

    // Training
    MODULE_COMPLETED,
    QUIZ_PASSED,
    QUIZ_FAILED,

    // Admin
    TRAINING_CREATED,
    TRAINING_UPDATED,
    TRAINING_ASSIGNED,
    USER_STATUS_CHANGED,
    USER_DELETED,
    PASS_SENT,
    PASS_PREVIEW_GENERATED,
    TRAINING_REVOKED
}